# Original code: https://github.com/theel0ja/Missing-Swedish-Roadnames-Finland/blob/cc0aed29fb6d54e37cddc51a484a18c172c934ed/.travis.yml
language: node_js

sudo: false

install:
  - yarn

script:
  - yarn build